# Generated by Django 5.2 on 2025-04-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='topic',
        ),
        migrations.AddField(
            model_name='newspaper',
            name='topics',
            field=models.ManyToManyField(related_name='newspapers', to='agency.topic'),
        ),
    ]
